### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by nidolight** [cvlab-stonybrook/local_learning_wsi#1]
Hello,

I am currently interested to participate in a [DACON competition](https://dacon.io/competitions/official/236011/overview/description) which try to classify the Lymph Node Metastasis.
※DACON is a platform similar to Kaggle

During my research, I found your article and just wanted to use your code and see what it does.
However, I do not see any license in your project. Thus, I do not know if this project is open source or not.
Additionally, I do not know if it is possible to contribute to this project? I am thinking of reorganizing the code to use it easily as an import, and not dealing with the script. This could be interesting, to have a modular project for future use case.

Thank you in advance for your response.

**Comment by jingweizhang-xyz** [comment]
Hi,

This project is open source and we are welcome to any modifications or pull request. 

Best,
Jingwei Zhang
