### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by thomascong121** [cvlab-stonybrook/local_learning_wsi#2]
Hi, thanks for the great work, I think this idea is very interesting, Do you mind sharing for the link to the datasets used in this paper?

**Comment by jingweizhang-xyz** [comment]
The datasets we used are all publicly available, TCGA-NSCLC consists of the diagnostic slides of TCGA-LUAD and TCGA-LUSC. TCGA-RCC consists of the the diagnostic slides of TCGA-KICH, TCGA-KIRC and TCGA-KIPR. They are available here https://portal.gdc.cancer.gov/. The LKS dataset is available here: https://github.com/cradleai/LKS-Dataset. It provides the preprocessing code.

**Comment by thomascong121** [comment]
Great, thanks for the clarification.
